/*
 * SPDX-License-Identifier: MIT
 * Copyright (c) 2026 Filip Sedivy
 *
 * The application object, shared by every scene.
 */
#pragma once

#include <furi.h>
#include <furi_hal.h>

#include <dialogs/dialogs.h>
#include <gui/gui.h>
#include <gui/scene_manager.h>
#include <gui/view_dispatcher.h>
#include <notification/notification_messages.h>
#include <storage/storage.h>

#include <gui/modules/byte_input.h>
#include <gui/modules/loading.h>
#include <gui/modules/number_input.h>
#include <gui/modules/popup.h>
#include <gui/modules/submenu.h>
#include <gui/modules/text_box.h>
#include <gui/modules/text_input.h>
#include <gui/modules/variable_item_list.h>
#include <gui/modules/widget.h>

#include <lib/nfc/nfc.h>

/* Generated by fbt from the PNG files in images/. */
#include <emrtd_icons.h>

#include "emrtd.h"
#include "emrtd_error.h"
#include "scenes/emrtd_scene.h"
#include "views/emrtd_date_input.h"
#include "views/emrtd_read_view.h"
#include "worker/emrtd_export.h"
#include "worker/emrtd_worker.h"

#ifdef __cplusplus
extern "C" {
#endif

#define EMRTD_TEXT_STORE_SIZE 256

/** Custom events. Values below 100 are reserved for widget button indices. */
typedef enum {
    EmrtdCustomEventReserved = 100,

    EmrtdCustomEventViewExit,
    EmrtdCustomEventTextInputDone,
    EmrtdCustomEventDateInputDone,
    EmrtdCustomEventNumberInputDone,

    /* Posted from the NFC thread by the worker callback. */
    EmrtdCustomEventWorkerProgress,
    EmrtdCustomEventWorkerAuthenticated,
    EmrtdCustomEventWorkerSuccess,
    EmrtdCustomEventWorkerError,
} EmrtdCustomEvent;

/** Which date the shared date input is editing. */
typedef enum {
    EmrtdDateFieldBirth,
    EmrtdDateFieldExpiry,
} EmrtdDateField;

typedef enum {
    EmrtdViewSubmenu,
    EmrtdViewVariableItemList,
    EmrtdViewPopup,
    EmrtdViewLoading,
    EmrtdViewTextInput,
    EmrtdViewNumberInput,
    EmrtdViewTextBox,
    EmrtdViewWidget,
    EmrtdViewDateInput,
    EmrtdViewRead,
} EmrtdView;

struct Emrtd {
    Gui* gui;
    ViewDispatcher* view_dispatcher;
    SceneManager* scene_manager;
    NotificationApp* notifications;
    Storage* storage;
    DialogsApp* dialogs;

    /* Stock views. */
    Submenu* submenu;
    VariableItemList* variable_item_list;
    Popup* popup;
    Loading* loading;
    TextInput* text_input;
    NumberInput* number_input;
    TextBox* text_box;
    Widget* widget;

    /* Views of our own. */
    EmrtdDateInput* date_input;
    EmrtdReadView* read_view;

    /* Scratch shared by the scenes. */
    char text_store[EMRTD_TEXT_STORE_SIZE];
    FuriString* text_box_store;
    FuriString* file_path;

    /* Settings, persisted to EMRTD_SETTINGS_PATH. */
    EmrtdWorkerConfig config;
    bool remember_credentials;

    /* The read in progress and what it produced. */
    Nfc* nfc;
    EmrtdWorker* worker;
    EmrtdWorkerProgress progress;
    EmrtdReadResult result;

    /* Navigation state. */
    EmrtdDateField date_field;
    EmrtdFileId selected_file;
};

/* --- Helpers shared by the scenes --------------------------------------- */

void emrtd_text_store_set(Emrtd* app, const char* format, ...);
void emrtd_text_store_clear(Emrtd* app);

/** Slow blink on the LED while the field is on. */
void emrtd_blink_start(Emrtd* app);
void emrtd_blink_stop(Emrtd* app);

void emrtd_notify_success(Emrtd* app);
void emrtd_notify_error(Emrtd* app);

/** Load and save the entered credentials and options. */
bool emrtd_settings_load(Emrtd* app);
bool emrtd_settings_save(Emrtd* app);
bool emrtd_settings_delete(Emrtd* app);

#ifdef __cplusplus
}
#endif
